# Generated by Django 4.2 on 2023-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
